# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-03 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('data', models.FileField(null=True, upload_to='uploads/')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot', models.IntegerField()),
                ('start_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now=True)),
                ('friends', models.ManyToManyField(through='snapshare_api.Friendship', to='snapshare_api.Person')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='snapshare_api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(to='snapshare_api.Topic'),
        ),
        migrations.AddField(
            model_name='person',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ManyToManyField(to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellows', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='preferences',
            field=models.ManyToManyField(to='snapshare_api.Topic'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='suitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='snapshare_api.Topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snapshare_api.Content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snapshare_api.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='related',
            field=models.ManyToManyField(to='snapshare_api.Person'),
        ),
    ]
